version: 2
updates:
  # backend（Gradle）
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10

  # frontend（pnpm）
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
