schemaspy.t=pgsql11
schemaspy.dp=/drivers_inc
schemaspy.host=postgres-db
schemaspy.port=5432
schemaspy.db=web_gallery
schemaspy.u=postgres
schemaspy.p=postgres
schemaspy.s=common
schemaspy.o=/output/common
