@startuml
title <size:24>Infrastructure</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("WebGalleryApplication_boundary", "WebGalleryApplication", $tags="") {
  Container_Boundary("WebGalleryApplication.WebGalleryApplication_boundary", "WebGalleryApplication", $tags="") {
    Component(WebGalleryApplication.WebGalleryApplication.Domain, "Domain", $techn="Module", $descr="", $tags="", $link="")
    Component(WebGalleryApplication.WebGalleryApplication.Application, "Application", $techn="Module", $descr="", $tags="", $link="")
    Component(WebGalleryApplication.WebGalleryApplication.Infrastructure, "Infrastructure", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(WebGalleryApplication.WebGalleryApplication.Application, WebGalleryApplication.WebGalleryApplication.Domain, "uses", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Infrastructure, WebGalleryApplication.WebGalleryApplication.Domain, "listens to", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Infrastructure, WebGalleryApplication.WebGalleryApplication.Application, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml