@startuml
title <size:24>Repository</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("WebGalleryApplication_boundary", "WebGalleryApplication", $tags="") {
  Container_Boundary("WebGalleryApplication.WebGalleryApplication_boundary", "WebGalleryApplication", $tags="") {
    Component(WebGalleryApplication.WebGalleryApplication.Mapper, "Mapper", $techn="Module", $descr="", $tags="", $link="")
    Component(WebGalleryApplication.WebGalleryApplication.Model, "Model", $techn="Module", $descr="", $tags="", $link="")
    Component(WebGalleryApplication.WebGalleryApplication.Repository, "Repository", $techn="Module", $descr="", $tags="", $link="")
    Component(WebGalleryApplication.WebGalleryApplication.Dto, "Dto", $techn="Module", $descr="", $tags="", $link="")
    Component(WebGalleryApplication.WebGalleryApplication.Entity, "Entity", $techn="Module", $descr="", $tags="", $link="")
    Component(WebGalleryApplication.WebGalleryApplication.Enumuration, "Enumuration", $techn="Module", $descr="", $tags="", $link="")
    Component(WebGalleryApplication.WebGalleryApplication.Exception, "Exception", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(WebGalleryApplication.WebGalleryApplication.Exception, WebGalleryApplication.WebGalleryApplication.Enumuration, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Model, WebGalleryApplication.WebGalleryApplication.Enumuration, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Model, WebGalleryApplication.WebGalleryApplication.Entity, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Model, WebGalleryApplication.WebGalleryApplication.Dto, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Dto, WebGalleryApplication.WebGalleryApplication.Enumuration, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Mapper, WebGalleryApplication.WebGalleryApplication.Entity, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Mapper, WebGalleryApplication.WebGalleryApplication.Dto, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Entity, WebGalleryApplication.WebGalleryApplication.Enumuration, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Entity, WebGalleryApplication.WebGalleryApplication.Model, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Repository, WebGalleryApplication.WebGalleryApplication.Model, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Repository, WebGalleryApplication.WebGalleryApplication.Exception, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Repository, WebGalleryApplication.WebGalleryApplication.Enumuration, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Repository, WebGalleryApplication.WebGalleryApplication.Entity, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Repository, WebGalleryApplication.WebGalleryApplication.Dto, "depends on", $techn="", $tags="", $link="")
Rel(WebGalleryApplication.WebGalleryApplication.Repository, WebGalleryApplication.WebGalleryApplication.Mapper, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml